version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# open http://localhost:8555/ in browser

services:
  mysql_db:
    image: mysql:5.7
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bi_solutions
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - app-tier
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 5

  python_app:
    build: ""
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - "8555:8080"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge